### ISSUE TITLE
Test fails on WSL

### ISSUE THREAD

**Issue by martinvahi** [shinh/elvm#106]
The full console output MIGHT be downloadable from [this link](https://temporary.softf1.com/2021/bugs/2021_04_21_14-30-12_ELVM_revision_709bea7963848fca1439268ab97d7eb174f7681b_test_failure_console_output.txt), but the revision is 709bea7963848fca1439268ab97d7eb174f7681b and probably the most interesting console output lines are:

  
    (diff -u out/elc.c.eir.out out/elc.c.eir.tex.out > out/elc.c.eir.tex.out.diff.tmp && mv out/elc.c.eir.tex.out.diff.tmp out/elc.c.eir.tex.out.diff) || (cat out/elc.c.eir.tex.out.diff.tmp ; false)
    --- out/elc.c.eir.out   2021-04-22 08:11:40.740335000 +0300
    +++ out/elc.c.eir.tex.out       2021-04-22 11:34:47.693720200 +0300
    @@ -1,63 +1,2 @@
     === test/elc.in ===
    -var main = function(getchar, putchar) {
    -var a = 0;
    -var b = 0;
    -var c = 0;
    -var d = 0;
    -var bp = 0;
    -var sp = 0;
    -var pc = 0;
    -var mem = new Int32Array(1 << 24);
    -mem[0] = 1;
    -var running = true;
    -
    -var func0 = function() {
    - while (0 <= pc && pc < 512 && running) {
    -  switch (pc) {
    -  case -1:  // dummy
    -   break;
    -
    -  case 0:
    -   if (true) pc = 1 - 1;
    -   break;
    -
    -  case 1:
    -   a = getchar();
    -   if (a == 0) pc = 3 - 1;
    -   break;
    -
    -  case 2:
    -   putchar(a);
    -   if (true) pc = 1 - 1;
    -   break;
    -
    -  case 3:
    -   running = false; break;
    -  }
    -  pc++;
    - }
    -};
    -
    -while (running) {
    - switch (pc / 512 | 0) {
    - case 0:
    -  func0();
    -  break;
    - }
    -}
    -};
    -if (typeof require != 'undefined') {
    - var sys = require('sys');
    - var input = null;
    - var ip = 0;
    - var getchar = function() {
    -  if (input === null)
    -   input = require('fs').readFileSync('/dev/stdin');
    -  return input[ip++] | 0;
    - };
    - var putchar = function(c) {
    -  sys.print(String.fromCharCode(c & 255));
    - };
    - main(getchar, putchar);
    -}
    
    diff.mk:4: recipe for target 'out/elc.c.eir.tex.out.diff' failed
    make: *** [out/elc.c.eir.tex.out.diff] Error 1

I used 

    make -j 3

for building. The environment:

    tsw1@DESKTOP-H12EA8D:~/m_local/bin_p/ELVM/v2021_04_08/elvm$ uname -a
    Linux DESKTOP-H12EA8D 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 GNU/Linux
    tsw1@DESKTOP-H12EA8D:~/m_local/bin_p/ELVM/v2021_04_08/elvm$ gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)

**Comment by shinh** [comment]
This is a quick fix: https://github.com/shinh/elvm/commit/9e30ac5cedb35edb343e644eb09eef8847710933

Anyway, it would be not easy to get `make test` passed as some backends need prerequisite and/or are broken. I'd recommended you to build and test a specific backend you are interested in. You can build and test tex backend by `make tex`.
