### ISSUE TITLE
Let this project support Windows?

### ISSUE THREAD

**Issue by none-None1** [shinh/elvm#132]
This project only supports Linux, so I have to copy it to a virtual machine to execute it, why not let it support Windows?

**Comment by GNUfan42** [comment]
Couldn't it be compiled with MSYS2 or Cygwin?

**Comment by none-None1** [comment]
No, some functions like `waitpid()` in the source code are unsupported in Windows.

**Comment by GNUfan42** [comment]
Just tried it, ELVM compiles and runs in Cygwin64 out-of-the-box.
![elvm_cygwin64](https://github.com/shinh/elvm/assets/70456172/8be91b9b-26a2-43b7-93fb-f9fb27bd536f)

**Comment by none-None1** [comment]
Thanks!
