### ISSUE TITLE
Query: befunge implementation quality

### ISSUE THREAD

**Issue by serprex** [shinh/elvm#14]
I maintain some fast Befunge implementations: https://github.com/serprex/befunge

Would you be interested in accepting a PR where I've modified [bejit](https://github.com/serprex/Befunge/blob/master/bejit.c) to match befunge.cc's lack of bounding area? Would it be preferable if I weren't using indirect gotos?

**Comment by shinh** [comment]
Yes, definitely I'm interested! Befunge backend is one of the slowest backends and my befunge.cc wasn't optimized. Your bejit looks indeed very interesting. I like it properly handles self-modifying code like "<vp11*88". I'd like to study how it works.

I'm fine with indirect gotos.

**Comment by serprex** [comment]
I've got a basic version working: https://github.com/serprex/Befunge/blob/master/bejit-elvm.cc

Benchmark of https://github.com/catseye/Befunge-93/blob/master/eg/mandel.bf
Bejit: ~0.48s
Bejit-elvm: ~2.62s
Befunge-elvm: ~3.29s

mandel.bf greatly benefits from constant propagation, which I haven't ported in this MVP version. Bejit-elvm contains no peepholer & probably shows that I've written nearly no C++ before now. I think before adding constant propagation the first step to optimize would be to inline all the pop logic to try leverage C++'s stack's emplace method. The implementation also carries a bug: it doesn't increase bounds of program if `p` writes outside the original program space

**Comment by shinh** [comment]
Great, thanks for your work! I thought your optimization would be more effective for machine generated code than for hand-written code. My guess was right. Benchmark results for ToT 8cc.bef:

Bejit-elvm: 9.85s
Befunge-elvm: 161.93s (>16x speedup!)

This is already impressive speed-up! I'm happy to accept your PR even without further optimization.

If you are interested in running a benchmark for a huge befunge program, you could try something like

$ wget http://shinh.skr.jp/elvm/8cc.c.eir.bef
$ echo 'int main() {}' | time ./bejit-elvm 8cc.c.eir.bef

Note this is 8cc was generated with older ELVM and is much faster (I'm in a stupid hotel right now which doesn't allow me to update it :( ). I still saw your bejit-elvm is >6x faster than mine with the uploaded version of 8cc anyway.

I still don't know how your original bejit works, but constant propagation sounds great. I think about half of code generated by ELVM is just calculating a big constant value by multiplying 9. I'm not sure about stack check either. I think ELVM generated code never tries to use empty stack, so I'd imagine branch prediction would also succeed.

Hmm it's shame my interpreter cannot run beer6 properly.

**Comment by serprex** [comment]
The current code generator would really benefit from using strings instead of only numbers. `9999*** == "QQ"*`

**Comment by serprex** [comment]
#18
