### ISSUE TITLE
Build errors with GCC 7

### ISSUE THREAD

**Issue by DennisMitchell** [shinh/elvm#47]
Starting with version 7, GCC generates a warning for `case` statements without a `break`, such as line 419ff or `ir/ir.c`:

```c
  switch (op) {
    case LOAD:
    case STORE:
      if (g_split_basic_block_by_mem) {
        p->pc++;
        p->prev_boundary = true;
      }
```

Since the default compilation options of the Makefile include `-Werror`, this prevents building most of the toolchain. The easiest fix might be to add `-Wno-implicit-fallthrough` to `COMMONFLAGS`.

**Comment by shinh** [comment]
I think this was fixed.
