### ISSUE TITLE
Problem with `make`

### ISSUE THREAD

**Issue by RustemB** [shinh/elvm#87]
![image](https://user-images.githubusercontent.com/25725953/87352708-f4abcf00-c574-11ea-8c80-c57f8c69b266.png)
```
$ make
```
does not work

**Comment by kneelian** [comment]
I am not getting this anymore, on the version checked out today.

**Comment by RustemB** [comment]
i got the same error again

**Comment by Scoder12** [comment]
Try `make 'COMMONFLAGS=-W -Wall -W -MMD -MP -O -g -Wno-missing-field-initializers'`
It's the regular `COMMONFLAGS` from the `Makefile` with `-Werror` omitted.

**Comment by RustemB** [comment]
kk, this works now (but fails 'because I don't have ruby)

**Comment by Scoder12** [comment]
I don't think it's failing just warning. I don't have ruby either and it works for me.

**Comment by Scoder12** [comment]
Try just `make out/elc` and see if it works

**Comment by wgaylord** [comment]
This is still an issue currently. You have to run make was `make 'COMMONFLAGS=-W -Wall -W -MMD -MP -O -g -Wno-missing-field-initializers` or it fails.

**Comment by woodrush** [comment]
I've confirmed that #121 fixes this issue. It is now under a pull request.
